#!/usr/bin/env python3
"""
Potential Fields 2D — TurtleBot3 Burger + ROS2 Humble
============================================================
Goal-seeking with obstacle avoidance in a 2D vector field.

Obstacles and goal are at KNOWN positions in the odom frame.
The robot starts at the origin (0,0,0) each run.

The node:
  1. Reads robot pose from /odom
  2. Computes attractive force toward goal + repulsive force
     from each obstacle  ->  total 2D force vector
  3. Steers the differential drive toward that force vector

Students: DO NOT edit this file.
          Change scenarios using YAML config files in config/.

Tested on: TurtleBot3 Burger, ROS2 Humble
============================================================
"""

import rclpy
from rclpy.node import Node
from rclpy.qos import QoSProfile, ReliabilityPolicy, HistoryPolicy
import numpy as np
import math

from nav_msgs.msg import Odometry, Path
from geometry_msgs.msg import Twist, Point, PoseStamped
from std_msgs.msg import Float32MultiArray, String
from visualization_msgs.msg import Marker, MarkerArray
import json


class PotentialField2D(Node):
    def __init__(self):
        super().__init__('potential_field_2d')

        # ============================================================
        #   PARAMETERS  (set via YAML scenario files)
        # ============================================================
        # Field gains
        self.declare_parameter('k_att',            1.0)
        self.declare_parameter('k_rep',            0.6)
        self.declare_parameter('influence_radius', 0.8)   # d0 per obstacle

        # Goal position in odom frame (metres)
        self.declare_parameter('goal_x',           2.0)
        self.declare_parameter('goal_y',           0.0)
        self.declare_parameter('goal_tolerance',   0.15)

        # Obstacles: flat list [x1, y1, x2, y2, ...] in odom frame
        self.declare_parameter('obstacles',        [1.0, 0.0])

        # Rotational field escape (toggle + strength)
        self.declare_parameter('rotational_field', False)
        self.declare_parameter('k_rot',            0.5)

        # Motion limits
        self.declare_parameter('max_lin_speed',    0.15)
        self.declare_parameter('max_ang_speed',    1.0)
        self.declare_parameter('heading_gain',     1.5)   # P-gain on heading
        self.declare_parameter('w_slew',           0.25)  # max change in w per cycle

        # Bookkeeping
        self.declare_parameter('scenario_name',    'scenario')

        # ---- read them ----
        self.k_att      = self.get_parameter('k_att').value
        self.k_rep      = self.get_parameter('k_rep').value
        self.d0         = self.get_parameter('influence_radius').value
        self.goal       = np.array([
            self.get_parameter('goal_x').value,
            self.get_parameter('goal_y').value])
        self.goal_tol   = self.get_parameter('goal_tolerance').value

        obs_flat        = self.get_parameter('obstacles').value
        self.obstacles  = np.array(obs_flat, dtype=float).reshape(-1, 2)

        self.use_rot    = self.get_parameter('rotational_field').value
        self.k_rot      = self.get_parameter('k_rot').value

        self.v_max      = self.get_parameter('max_lin_speed').value
        self.w_max      = self.get_parameter('max_ang_speed').value
        self.h_gain     = self.get_parameter('heading_gain').value
        self.w_slew     = self.get_parameter('w_slew').value

        self.scenario   = self.get_parameter('scenario_name').value

        # ============================================================
        #   STATE
        # ============================================================
        self.pose = None            # [x, y, theta] in the START frame
        self.reached = False
        self.stuck_count = 0
        self.w_prev = 0.0           # last angular command (for slew limit)
        self.turn_sign = 0          # committed turn direction near 180 deg
        self.start_time = self.get_clock().now()

        # Origin capture. /odom accumulates across runs, so the very first
        # reading of THIS run is taken as the origin and every pose is
        # expressed relative to it. The robot therefore always starts at
        # (0,0,0) in the field frame, whatever odom happens to report, and
        # there is no need to restart bringup between scenarios.
        self.have_origin = False
        self.x0 = 0.0
        self.y0 = 0.0
        self.th0 = 0.0
        self.raw_pos = np.zeros(2)  # latest raw odom position (for markers)
        self.raw_yaw = 0.0          # latest raw odom heading (for the path)

        # ============================================================
        #   ROS INTERFACE
        # ============================================================
        qos = QoSProfile(
            reliability=ReliabilityPolicy.BEST_EFFORT,
            history=HistoryPolicy.KEEP_LAST,
            depth=10)

        self.cmd_pub   = self.create_publisher(Twist,             '/cmd_vel',    10)
        self.debug_pub = self.create_publisher(Float32MultiArray, '/pf2d_debug', 10)
        self.status_pub= self.create_publisher(String,            '/pf2d_status',10)
        self.marker_pub= self.create_publisher(MarkerArray,       '/pf2d_markers',10)
        self.path_pub  = self.create_publisher(Path,              '/pf2d_path',  10)

        # frame the markers live in (odom, same as the pose we read)
        self.frame_id  = 'odom'

        # continuous trajectory trace, grows as the robot drives
        self.path_msg = Path()
        self.path_msg.header.frame_id = self.frame_id

        # /odom on TB3 is reliable by default, but BEST_EFFORT sub is
        # compatible with both a reliable and a best-effort publisher.
        self.odom_sub = self.create_subscription(
            Odometry, '/odom', self.odom_callback, qos)

        self.timer = self.create_timer(0.1, self.control_loop)

        self._log_startup()

    # ================================================================
    #   STARTUP LOG
    # ================================================================
    def _log_startup(self):
        self.get_logger().info('=' * 58)
        self.get_logger().info('  POTENTIAL FIELDS 2D — Node Started')
        self.get_logger().info('=' * 58)
        self.get_logger().info(f'  Scenario   : {self.scenario}')
        self.get_logger().info(f'  Goal       : ({self.goal[0]}, {self.goal[1]}) m')
        self.get_logger().info(f'  Obstacles  : {len(self.obstacles)}')
        for i, o in enumerate(self.obstacles):
            self.get_logger().info(f'     obs[{i}]  : ({o[0]:.2f}, {o[1]:.2f})')
        self.get_logger().info(f'  k_att={self.k_att}  k_rep={self.k_rep}  d0={self.d0}')
        self.get_logger().info(f'  Rotational field: {self.use_rot}  (k_rot={self.k_rot})')
        self.get_logger().info('=' * 58)
        self.get_logger().info('  Waiting for /odom ...')

    # ================================================================
    #   ODOM
    # ================================================================
    def odom_callback(self, msg):
        p = msg.pose.pose.position
        q = msg.pose.pose.orientation
        # yaw from quaternion
        siny = 2.0 * (q.w * q.z + q.x * q.y)
        cosy = 1.0 - 2.0 * (q.y * q.y + q.z * q.z)
        yaw = math.atan2(siny, cosy)

        # first reading of this run defines the origin
        if not self.have_origin:
            self.x0, self.y0, self.th0 = p.x, p.y, yaw
            self.have_origin = True
            self.get_logger().info(
                f'  Origin captured at odom ({p.x:.2f}, {p.y:.2f}, '
                f'{math.degrees(yaw):.0f} deg). Field frame starts here.')

        self.raw_pos = np.array([p.x, p.y])
        self.raw_yaw = yaw

        # express the pose in the START frame: translate by the origin,
        # then rotate by -th0 so the initial heading is +x
        c, s = math.cos(self.th0), math.sin(self.th0)
        dx, dy = p.x - self.x0, p.y - self.y0
        xr = c * dx + s * dy
        yr = -s * dx + c * dy
        thr = self._wrap(yaw - self.th0)
        self.pose = np.array([xr, yr, thr])

    def _to_odom(self, pf):
        """Map a point from the START frame back into the odom frame,
        so RViz markers line up with the robot's odom pose."""
        c, s = math.cos(self.th0), math.sin(self.th0)
        return (self.x0 + c * pf[0] - s * pf[1],
                self.y0 + s * pf[0] + c * pf[1])

    # ================================================================
    #   FIELD COMPUTATION
    # ================================================================
    def attractive_force(self, pos):
        """Attractive force toward goal.
        Constant magnitude far away (conical), eases off within 1 m."""
        diff = self.goal - pos
        dist = np.linalg.norm(diff)
        if dist < 1e-6:
            return np.zeros(2)
        if dist > 1.0:
            return self.k_att * diff / dist
        return self.k_att * diff

    def repulsive_force(self, pos):
        """Sum of Khatib repulsive forces from each obstacle."""
        total = np.zeros(2)
        for obs in self.obstacles:
            diff = pos - obs           # points AWAY from obstacle
            dist = np.linalg.norm(diff)
            if dist < 1e-6 or dist >= self.d0:
                continue
            direction = diff / dist
            mag = self.k_rep * (1.0 / dist - 1.0 / self.d0) * (1.0 / (dist * dist))
            total += mag * direction
        return total

    def rotational_force(self, pos):
        """Optional tangential field to escape local minima.
        Rotates each obstacle's repulsive direction by +90 degrees."""
        if not self.use_rot:
            return np.zeros(2)
        total = np.zeros(2)
        for obs in self.obstacles:
            diff = pos - obs
            dist = np.linalg.norm(diff)
            if dist < 1e-6 or dist >= self.d0:
                continue
            direction = diff / dist
            tangent = np.array([-direction[1], direction[0]])  # rotate +90 deg
            mag = self.k_rot * (1.0 / dist - 1.0 / self.d0)
            total += mag * tangent
        return total

    def total_force(self, pos):
        return (self.attractive_force(pos)
                + self.repulsive_force(pos)
                + self.rotational_force(pos))

    # ================================================================
    #   CONTROL LOOP
    # ================================================================
    def control_loop(self):
        if self.pose is None:
            return

        pos = self.pose[:2]
        theta = self.pose[2]
        elapsed = (self.get_clock().now() - self.start_time).nanoseconds / 1e9

        dist_to_goal = np.linalg.norm(self.goal - pos)

        # ---- goal reached ----
        if dist_to_goal < self.goal_tol:
            if not self.reached:
                self.get_logger().info('-' * 58)
                self.get_logger().info(f'  GOAL REACHED at ({pos[0]:.2f}, {pos[1]:.2f})')
                self.get_logger().info('-' * 58)
                self.reached = True
            self.stop()
            self._publish(pos, np.zeros(2), 0.0, 0.0, elapsed, 'REACHED')
            return

        # ---- compute field ----
        force = self.total_force(pos)
        fmag = np.linalg.norm(force)

        # ---- detect local-minimum stall ----
        if fmag < 0.05:
            self.stuck_count += 1
            if self.stuck_count == 15:
                self.get_logger().warn('-' * 58)
                self.get_logger().warn(f'  LOCAL MINIMUM — robot stuck at '
                                       f'({pos[0]:.2f}, {pos[1]:.2f})')
                self.get_logger().warn(f'  |F| = {fmag:.4f}, goal not reached.')
                if not self.use_rot:
                    self.get_logger().warn('  Enable rotational_field to escape.')
                self.get_logger().warn('-' * 58)
            self.stop()
            self._publish(pos, force, 0.0, 0.0, elapsed, 'STUCK')
            return
        else:
            self.stuck_count = 0

        # ---- convert force vector to differential-drive command ----
        desired_heading = math.atan2(force[1], force[0])
        heading_err = self._wrap(desired_heading - theta)

        # Robust steering. A plain P-controller dithers when the target is
        # almost directly behind the robot (heading_err near +/-pi) and hunts
        # when the gain is high. Three guards fix that:
        if abs(heading_err) < 0.05:
            w = 0.0                       # deadband: stop twitching near aligned
            self.turn_sign = 0
        elif abs(heading_err) > 2.8:
            # target ~180 deg behind: commit one turn direction instead of
            # flip-flopping left/right and never translating
            if self.turn_sign == 0:
                self.turn_sign = 1.0 if heading_err > 0.0 else -1.0
            w = self.turn_sign * self.w_max
        else:
            self.turn_sign = 0
            w = float(np.clip(self.h_gain * heading_err, -self.w_max, self.w_max))

        # slew-rate limit so w cannot slam between extremes cycle to cycle
        dw = float(np.clip(w - self.w_prev, -self.w_slew, self.w_slew))
        w = self.w_prev + dw
        self.w_prev = w

        forward_scale = max(0.0, math.cos(heading_err))
        v = float(np.clip(self.v_max * forward_scale, 0.0, self.v_max))

        cmd = Twist()
        cmd.linear.x = v
        cmd.angular.z = w
        self.cmd_pub.publish(cmd)

        self._publish(pos, force, v, w, elapsed, 'RUNNING')

        self.get_logger().info(
            f't={elapsed:5.1f}s | pos=({pos[0]:5.2f},{pos[1]:5.2f}) | '
            f'|F|={fmag:5.2f} | dg={dist_to_goal:4.2f} | v={v:.2f} w={w:+.2f}')

    # ================================================================
    #   HELPERS
    # ================================================================
    @staticmethod
    def _wrap(angle):
        return math.atan2(math.sin(angle), math.cos(angle))

    def _publish(self, pos, force, v, w, t, state):
        # debug: [t, x, y, Fx, Fy, v, w, dist_to_goal]
        msg = Float32MultiArray()
        msg.data = [float(t), float(pos[0]), float(pos[1]),
                    float(force[0]), float(force[1]),
                    float(v), float(w),
                    float(np.linalg.norm(self.goal - pos))]
        self.debug_pub.publish(msg)

        status = {
            'state': state,
            'scenario': self.scenario,
            'time': round(t, 2),
            'pos': [round(float(pos[0]), 3), round(float(pos[1]), 3)],
            'force': [round(float(force[0]), 3), round(float(force[1]), 3)],
        }
        s = String()
        s.data = json.dumps(status)
        self.status_pub.publish(s)

        self._publish_markers(pos, force)
        self._publish_path()

    def _publish_path(self):
        """Grow a nav_msgs/Path with the robot's odom pose, so RViz can draw
        one continuous line. A new point is added only after ~1 cm of motion,
        which keeps the message small and leaves a visible scribble wherever
        the robot stalls."""
        stamp = self.get_clock().now().to_msg()
        add = not self.path_msg.poses
        if not add:
            last = self.path_msg.poses[-1].pose.position
            if math.hypot(self.raw_pos[0] - last.x,
                          self.raw_pos[1] - last.y) > 0.01:
                add = True
        if add:
            ps = PoseStamped()
            ps.header.frame_id = self.frame_id
            ps.header.stamp = stamp
            ps.pose.position.x = float(self.raw_pos[0])
            ps.pose.position.y = float(self.raw_pos[1])
            ps.pose.orientation.z = math.sin(self.raw_yaw / 2.0)
            ps.pose.orientation.w = math.cos(self.raw_yaw / 2.0)
            self.path_msg.poses.append(ps)
        self.path_msg.header.stamp = stamp
        self.path_pub.publish(self.path_msg)

    def _publish_markers(self, pos, force):
        """RViz visuals in the odom frame: goal, obstacles, each obstacle's
        influence ring (d0), and the live total-force arrow at the robot.
        None of this feeds the controller — it is purely for display."""
        arr = MarkerArray()
        stamp = self.get_clock().now().to_msg()
        mid = 0

        def new_marker(mtype):
            nonlocal mid
            m = Marker()
            m.header.frame_id = self.frame_id
            m.header.stamp = stamp
            m.ns = 'pf2d'
            m.id = mid
            m.type = mtype
            m.action = Marker.ADD
            m.pose.orientation.w = 1.0
            mid += 1
            return m

        # goal, obstacles and rings are defined in the START frame, so map
        # each one back into odom for display alongside the robot's odom pose
        gx, gy = self._to_odom(self.goal)

        # --- goal: green sphere ---
        g = new_marker(Marker.SPHERE)
        g.pose.position.x = gx
        g.pose.position.y = gy
        g.scale.x = g.scale.y = g.scale.z = 0.18
        g.color.g = 1.0; g.color.a = 1.0
        arr.markers.append(g)

        # --- obstacles: red cylinders + dashed influence ring at d0 ---
        for obs in self.obstacles:
            ox, oy = self._to_odom(obs)
            c = new_marker(Marker.CYLINDER)
            c.pose.position.x = ox
            c.pose.position.y = oy
            c.scale.x = c.scale.y = 0.16
            c.scale.z = 0.30
            c.pose.position.z = 0.15
            c.color.r = 1.0; c.color.a = 0.9
            arr.markers.append(c)

            ring = new_marker(Marker.LINE_STRIP)
            ring.scale.x = 0.015          # line width
            ring.color.r = 1.0; ring.color.g = 0.6; ring.color.a = 0.7
            for k in range(0, 49):
                ang = 2.0 * math.pi * k / 48.0
                px, py = self._to_odom((obs[0] + self.d0 * math.cos(ang),
                                        obs[1] + self.d0 * math.sin(ang)))
                p = Point(); p.x = px; p.y = py
                ring.points.append(p)
            arr.markers.append(ring)

        # --- total force: blue arrow anchored at the robot's odom pose ---
        a = new_marker(Marker.ARROW)
        a.scale.x = 0.03      # shaft diameter
        a.scale.y = 0.07      # head diameter
        a.scale.z = 0.08      # head length
        a.color.b = 1.0; a.color.r = 0.1; a.color.a = 1.0
        scale = 0.3           # metres of arrow per unit of |F|
        fmag = float(np.linalg.norm(force))
        length = min(0.6, scale * fmag)
        cth, sth = math.cos(self.th0), math.sin(self.th0)
        start = Point(); start.x = float(self.raw_pos[0]); start.y = float(self.raw_pos[1]); start.z = 0.05
        end = Point(); end.z = 0.05
        if fmag > 1e-6:
            # rotate the (field-frame) force direction into odom
            fxo = (force[0] * cth - force[1] * sth) / fmag
            fyo = (force[0] * sth + force[1] * cth) / fmag
            end.x = float(self.raw_pos[0] + length * fxo)
            end.y = float(self.raw_pos[1] + length * fyo)
        else:
            end.x = float(self.raw_pos[0]); end.y = float(self.raw_pos[1])
        a.points = [start, end]
        arr.markers.append(a)

        # --- text labels (namespace 'pf2d_labels'; one marker PER LINE, since
        #     this RViz does not honour '\n' and would sprawl the text) ---
        TXT_H = 0.07                               # text height in metres
        DARK = (0.15, 0.15, 0.15)                  # reads on red/green fills

        def new_text(px, py, text, color):
            nonlocal mid
            t = Marker()
            t.header.frame_id = self.frame_id
            t.header.stamp = stamp
            t.ns = 'pf2d_labels'
            t.id = mid; mid += 1
            t.type = Marker.TEXT_VIEW_FACING
            t.action = Marker.ADD
            t.pose.orientation.w = 1.0
            t.pose.position.x = px
            t.pose.position.y = py
            t.pose.position.z = 0.35             # float above the cylinders
            t.scale.z = TXT_H
            t.color.r, t.color.g, t.color.b = color
            t.color.a = 1.0
            t.text = text
            return t

        # goal coordinate, centred on the green sphere
        gx, gy = self._to_odom((self.goal[0], self.goal[1]))
        arr.markers.append(new_text(
            gx, gy, f'({self.goal[0]:.1f},{self.goal[1]:.1f})', DARK))

        # obstacle coordinate(s), centred on each red marker
        # (skip labels when the field is crowded, e.g. the canyon)
        if len(self.obstacles) <= 4:
            for obs in self.obstacles:
                ox, oy = self._to_odom((obs[0], obs[1]))
                arr.markers.append(new_text(
                    ox, oy, f'({obs[0]:.1f},{obs[1]:.2f})', DARK))

        # live robot readout: two short lines just below the robot
        dg = float(np.linalg.norm(self.goal - pos))
        rx, ry = float(self.raw_pos[0]), float(self.raw_pos[1])
        arr.markers.append(new_text(rx, ry - 0.16, f'dg={dg:.2f}',  (0.10, 0.20, 0.60)))
        arr.markers.append(new_text(rx, ry - 0.28, f'|F|={fmag:.2f}', (0.10, 0.20, 0.60)))

        self.marker_pub.publish(arr)

    def stop(self):
        self.cmd_pub.publish(Twist())
        self.w_prev = 0.0
        self.turn_sign = 0


def main(args=None):
    rclpy.init(args=args)
    node = PotentialField2D()
    try:
        rclpy.spin(node)
    except KeyboardInterrupt:
        node.get_logger().info('Interrupted — stopping robot.')
    finally:
        node.stop()
        node.destroy_node()
        if rclpy.ok():
            rclpy.shutdown()


if __name__ == '__main__':
    main()
